version: '3.8'

services:
  # PHP Service (Laravel)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_network
    depends_on:
      - postgres

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel_network
    depends_on:
      - app

  # PostgreSQL Service
  postgres:
    image: postgres:15-alpine
    container_name: laravel_postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - laravel_network

  # Composer Service (optional)
  composer:
    image: composer:2
    container_name: laravel_composer
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - postgres
    networks:
      - laravel_network
    command: composer install

# Docker Networks
networks:
  laravel_network:
    driver: bridge

# Volumes
volumes:
  postgres_data:
    driver: local
